dist: bionic
sudo: required

language: java

jdk:
- openjdk11

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

addons:
  chrome: stable

script:
- ./gradlew build --info

cache:
  directories:
  - $HOME/.m2
