pipelines:
    hello-world:
        group: example
        materials:
            hello-world-git:
                git: https://github.com/hamvocke/spring-testing.git
        stages:
            - build-and-test:
                secure_variables:
                    WEATHER_API_KEY: "bRaqcfbCt4E3eRMpJR/STGDBenHord2mj1Mn5+y9SCcJt6T0Qo9PnA=="
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: ./gradlew
                                arguments:
                                    - build

            - deploy-int:
                jobs:
                    deploy:
                        tasks:
                            - exec:
                                command: echo
                                arguments:
                                    - "Deploying to Int"
                    smoke-test:
                        tasks:
                            - exec:
                                command: echo
                                arguments:
                                    - "Running smoke tests"

            - end-to-end-test:
                jobs:
                    deploy:
                        tasks:
                            - exec:
                                command: echo
                                arguments:
                                    - "Running end to end tests"
