version: '2'
services:
  go-server:
    image: gocd/gocd-server:v17.4.0
    ports:
      - '8153:8153'
      - '8154:8154'
    volumes:
      - ./server/plugins/external:/godata/plugins/external
      - ./server/config/cruise-config.xml:/godata/config/cruise-config.xml
      - ./server/ssh:/var/go/.ssh

  goagent-java:
    build: 
      context: agent
      dockerfile: Dockerfile.java-agent
    links:
      - go-server
    environment:
      AGENT_AUTO_REGISTER_RESOURCES: 'java'
      GO_SERVER_URL: 'https://go-server:8154/go'
